# Generated by Django 5.0.3 on 2024-11-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="sora_UserInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=32, verbose_name="账户名称")),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                ("email", models.CharField(max_length=32, verbose_name="邮箱")),
                ("name", models.CharField(max_length=32, verbose_name="姓名")),
                ("phone", models.IntegerField(verbose_name="手机号码")),
                ("salt", models.CharField(max_length=128, verbose_name="salt")),
            ],
        ),
    ]
