# Generated by Django 5.0.3 on 2024-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_alter_sora_userinfo_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sora_userinfo",
            name="password",
            field=models.CharField(max_length=128, verbose_name="密码"),
        ),
    ]
